### ISSUE TITLE
Cannot send times/numbers in messages

### ISSUE THREAD

**Issue by jdmoore7** [AlfredoSequeida/etext#1]
My use case was texting myself arrivals times for a train. The 'Hello World!' example works great. However, if I use "15:25" as the message, the text will arrival with {MSG: ""} aka the message will not be delivered. What's this about?

**Comment by jdmoore7** [comment]
Actually, the character ':' cannot be used or the message will not send. No idea why this is the case, but numbers are fine without the colon.

**Comment by AlfredoSequeida** [comment]
That's really interesting. I haven't tested that myself. Have you tried escaping the character? Maybe something like this:

`"15\:25"`

Maybe that character means something special in one of the packages I used to send the email.
