### ISSUE TITLE
[SSL: WRONG_VERSION_NUMBER]

### ISSUE THREAD

**Issue by rapid3642** [AlfredoSequeida/etext#2]
Thank you for the package, it was helpful!

I ran into an issue where when I run this setup with an outlook account I received the error:
[SSL: WRONG_VERSION_NUMBER]

I was able to correct the issue by changing this:
    with smtplib.SMTP_SSL(
        smtp_server, smtp_port, context=ssl.create_default_context()
    ) as email:
        email.login(sender_email, email_password)
        email.sendmail(sender_email, receiver_email, email_message)

TO THIS:
    with smtplib.SMTP(
        smtp_server, smtp_port
    ) as email:
        email.starttls(context=ssl.SSLContext(ssl.PROTOCOL_TLS))
        email.login(sender_email, email_password)
        email.sendmail(sender_email, receiver_email, email_message)

I would like to provide the solution in the form of a commit, I will work on doing this :)

Also, I noticed you using port 465 as the default which is fine but just curious if you knew about port 587. Without typing it all out here is a great resource about it vs port 465:
https://sendgrid.com/blog/whats-the-difference-between-ports-465-and-587/

for this, I implemented starttls as well as mentioned in the article above :)

**Comment by AlfredoSequeida** [comment]
I'm glad it was helpful. It might be worth it to create a lookup table for different email providers or simply let the user pass in their own SSL instance to make this a more compatible library.
