### ISSUE TITLE
Question: which provider?

### ISSUE THREAD

**Issue by gilbh** [AlfredoSequeida/etext#3]
What should be the consideration for a specific provider?

**Comment by AlfredoSequeida** [comment]
> What should be the consideration for a specific provider?
@gilbh
I'm sorry, I don't understand the question. Can you elaborate a bit?

**Comment by gilbh** [comment]
Let me elaborate:

I gather the phone number has to match a specific provider, so I am wondering if there is a way to automatically figure out (query) which is the right provider for a specific phone number. If such a query can be done quickly (or be extracted from a pre-made list) then the user would not have to specify the provider on the function call. The code would do that for him/her.

I hope to above makes sense -- or maybe I got it wrong ... let me know what you think.

**Comment by AlfredoSequeida** [comment]
> Let me elaborate:
> 
> I gather the phone number has to match a specific provider, so I am wondering if there is a way to automatically figure out (query) which is the right provider for a specific phone number. If such a query can be done quickly (or be extracted from a pre-made list) then the user would not have to specify the provider on the function call. The code would do that for him/her.
> 
> I hope to above makes sense -- or maybe I got it wrong ... let me know what you think.

Got it, thank you for clarifying that. I know that there are carrier lookup services some free and some paid. I don't know how accurate they are or how they work exactly, but that's an option. With that said, an alternative to knowing the carrier might be to just send the same message to every provider using the same number. The incorrect matches will likely bounce back as failed messages, but the correct one will go through. If you're sending a lot of messages, it might be a good idea to check what the policies are for spam mail. I don't know if this could get your messages marked as spam. Also, I don't know if the possibility of multiple messages being delivered is a possibility. For example, I know that in the US, T-Mobile owns Sprint, so I don't know if a Sprint number will also receive messages from T-mobile's gateway. 

Here is a quick example of how you can achieve this using the included US providers.

```python
from etext import send_sms_via_email
from etext.providers import PROVIDERS

phone_number = "123-123-1234"
message = "hello world!"

sender_credentials = ("email@gmail.com", "email_password")

for provider in PROVIDERS:
    send_sms_via_email(
        phone_number, message, provider, sender_credentials, subject="sent using etext"
    )
```

**Comment by gilbh** [comment]
Yup, this looks like a straightforward solution, but I would be hesitant to send out automatically misconstrued sms/emails, exactly for the reason you mention, which is being marked as spam (after a few cycles probably). 

My own use for your nice code is to send sms messages to myself, (and I *know* which is my provider ;-), but I am just curious for sending to other phone numbers, when you really can't tell who the provider is (unless there is some web gateway?) .... a casual search found many such websites, although many seems to have captcha to avoid scrapes, I am wondering if there is one with an API like there should be... here's the search I did:
https://www.google.com/search?client=firefox-b-1-d&q=how+to+find+provider+of+a+phone+number

**Comment by AlfredoSequeida** [comment]
> Yup, this looks like a straightforward solution, but I would be hesitant to send out automatically misconstrued sms/emails, exactly for the reason you mention, which is being marked as spam (after a few cycles probably).
> 
> My own use for your nice code is to send sms messages to myself, (and I _know_ which is my provider ;-), but I am just curious for sending to other phone numbers, when you really can't tell who the provider is (unless there is some web gateway?) .... a casual search found many such websites, although many seems to have captcha to avoid scrapes, I am wondering if there is one with an API like there should be... here's the search I did: https://www.google.com/search?client=firefox-b-1-d&q=how+to+find+provider+of+a+phone+number

Unfortunately, since I have not done much research on the subject matter myself, I only know of one. However, it's a paid solution. 
https://www.twilio.com/lookup
