### ISSUE TITLE
Multiple MMS Messages at once?

### ISSUE THREAD

**Issue by jayecreates** [AlfredoSequeida/etext#4]
Is there any way to use this to take names and numbers from a .csv file and send multiple MMS messages at once?

**Comment by AlfredoSequeida** [comment]
Yes, you will just need to add that extra functionality. By default, the module only handles the sending functionality.

**Comment by AlfredoSequeida** [comment]
Yes, you will just need to add/code that extra functionality. The module only handles the sending functionality.
